### ISSUE TITLE
Netty version conflict issue

### ISSUE THREAD

**Issue by smartminghan** [coreos/jetcd#200] opened 2017-08-09 01:56 UTC
Hi, I use the jetcd previous version which use grpc 1.4.0 and met before exception.  It seems the issue of netty 4.1.11. May i know how to resolve it ?

java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:295)

**Comment by fanminshi** [comment] 2017-08-09 02:43
@smartminghan have you tried jetcd on the latest master?

**Comment by lburgazzoli** [comment] 2017-08-09 05:16
As far as I can remember the exception just tell you that jdk.internal.misc.Unsafe is not available but it is not a blocking one afaik, can you post your logs ?

**Comment by fanminshi** [comment] 2017-09-02 06:26
kindly ping @smartminghan

**Comment by PandaMonkey** [comment] 2018-02-05 14:20
@smartminghan Hi, Could you show your pom file? I am interested in such version conflict problems. Maybe I can help you identify the root cause. If you concern the privacy problem, you can also send it to my e-mail: pandamonkey1@sina.com

**Comment by lburgazzoli** [comment] 2018-04-24 05:34
@smartminghan I'm goging to close this since we've not received any more feedback

**Closed by lburgazzoli** 2018-04-24 05:34 UTC
