### ISSUE TITLE
invalid auth token

### ISSUE THREAD

**Issue by donsonHub** [coreos/jetcd#177] opened 2017-07-17 12:14 UTC
I init client like this,and then use it as a singleton to execute command like get、put、delete：
```
Client etcdClient = ClientBuilder.newBuilder().setEndpoints(endpointStr).setName(ByteSequence.fromString(name)).
                    setPassword( ByteSequence.fromString(password)).build();
```

but about after 5 minitus, when i execute command get、put or delete, I get the error: 
```
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: etcdserver: invalid auth token
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
		...
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: etcdserver: invalid auth token
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
        at com.coreos.jetcd.internal.impl.Util.lambda$listenableToCompletableFuture$2(Util.java:303)
        ... 3 more
Caused by: io.grpc.StatusRuntimeException: UNAUTHENTICATED: etcdserver: invalid auth token
        at io.grpc.Status.asRuntimeException(Status.java:543)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:442)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
        at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
```
so is the token is expired about 5 minitus latter? 

and there is a mechanism to update the client token?

**Comment by lburgazzoli** [comment] 2017-07-17 12:19
duplicate of #163

**Comment by xiang90** [comment] 2017-07-17 22:43
closing due to the duplication.

**Closed by xiang90** 2017-07-17 22:43 UTC
